from core.shared.exceptions import AlreadyExistsException


class OperationAlreadyExistException(AlreadyExistsException):
    pass
